import { BRIGHTOS_WALLPAPER_FILES } from './wallpapers';

export type BrightOSMission = {
  id: string;
  title: string;
  rank: 1 | 2 | 3 | 4 | 5;
  csec_alignment: {
    section: string;
    objective: string;
    concept: string;
  };
  client: {
    name: string;
    role: string;
    mood: 'Panic' | 'Angry' | 'Chill' | 'Confused';
    dialogue_start: string;
  };
  brightos_desktop: {
    device: 'Laptop' | 'Desktop';
    wallpaper_pool: string[];
    logo: {
      src: string;
      placement: 'top-left' | 'center' | 'bottom-right';
    };
    ui_preset: 'home_helper' | 'techfix_shop' | 'smallbiz_admin' | 'automation_lab' | 'csec_soc';
  };
  initial_state: {
    cpu_load: number;
    network_status: 'Connected' | 'Disconnected' | 'Slow';
    file_system: string[];
    terminal_history: string[];
  };
  tools_allowed: Array<'Terminal' | 'Task Manager' | 'Browser' | 'Settings' | 'Automation App'>;
  steps_to_solve: string[];
  success_condition: string;
  difficulty_tier: 1 | 2 | 3 | 4 | 5;
};

const WALLPAPERS = BRIGHTOS_WALLPAPER_FILES.map((f) => `/api/brightos/wallpaper/${encodeURIComponent(f)}`);

export const CSEC_ROADMAP_MISSIONS: BrightOSMission[] = [
  {
    id: 'tech-1',
    title: 'Welcome to the Digital Yard',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'User Interfaces (interface navigation)',
      concept: 'GUI Navigation / Window Management',
    },
    client: {
      name: 'Auntie Marva',
      role: 'Office Assistant',
      mood: 'Confused',
      dialogue_start: 'Bredda, the window stuck on my screen and I can’t click nuttin. Help nah?',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Documents/notes.txt'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Click the stuck window to focus it.',
      'Use the Close button (X) to close the stuck window.',
      'Re-open the Desktop and confirm the system responds normally.',
    ],
    success_condition: 'window.stuck_app.open == false',
    difficulty_tier: 1,
  },
  {
    id: 'tech-2',
    title: 'The Noisy Fan',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Process Management (use Task Manager)',
      concept: 'CPU Usage / Ending Processes',
    },
    client: {
      name: 'Uncle Dev',
      role: 'Taxi Driver',
      mood: 'Panic',
      dialogue_start: 'This laptop sounding like a jet! Something eating up all the CPU!',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 99,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Desktop/'],
      terminal_history: [],
    },
    tools_allowed: ['Task Manager'],
    steps_to_solve: [
      'Open Task Manager.',
      'Sort processes by CPU usage.',
      'Select the process using ~99% CPU.',
      'End Task for that process.',
    ],
    success_condition: 'cpu_load < 40 && process.high_cpu.running == false',
    difficulty_tier: 1,
  },
  {
    id: 'tech-3',
    title: 'Storage Crisis',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Terms associated with storage (disk full / temp files)',
      concept: 'Temporary Files / Recycle Bin',
    },
    client: {
      name: 'Ms. Keisha',
      role: 'Teacher',
      mood: 'Angry',
      dialogue_start: 'My SBA can’t save! It saying disk full and I have class now!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Connected',
      file_system: ['C:/Temp/cache1.tmp', 'C:/Temp/cache2.tmp', 'RecycleBin:/old_video.mp4'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open File Explorer.',
      'Navigate to the Temp folder.',
      'Delete all .tmp files.',
      'Empty the Recycle Bin.',
    ],
    success_condition: 'disk.free_space_mb >= 500 && files.tmp.count == 0 && recycle_bin.empty == true',
    difficulty_tier: 1,
  },
  {
    id: 'tech-4',
    title: 'The Lost Manifest',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'File Management (Search to find file in sub-folders)',
      concept: 'Search / Folder Navigation',
    },
    client: {
      name: 'Mr. Biswas',
      role: 'Shopkeeper',
      mood: 'Confused',
      dialogue_start: 'I save the invoice somewhere… but the folder dem too plenty. Find it for me nah.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: [
        'C:/Users/Student/Documents/Business/2026/Receipts/',
        'C:/Users/Student/Documents/Business/2026/Invoices/manifest_final.pdf',
      ],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open File Explorer.',
      'Use the Search box.',
      "Search for: 'manifest_final.pdf'",
      'Open the file from search results to confirm.',
    ],
    success_condition: 'file.opened == "manifest_final.pdf"',
    difficulty_tier: 1,
  },
  {
    id: 'tech-5',
    title: 'Driver Error',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Systems Software (Device Manager / update driver)',
      concept: 'Drivers / Audio Device',
    },
    client: {
      name: 'Tanesha',
      role: 'Student',
      mood: 'Panic',
      dialogue_start: 'Miss, the sound gone! I can’t hear the video for the lesson!',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 22,
      network_status: 'Connected',
      file_system: ['C:/System/Drivers/audio_driver.sys'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Device Manager.',
      'Expand Sound, video and game controllers.',
      'Select the Audio device.',
      'Choose Update driver.',
      'Complete the update and confirm audio returns.',
    ],
    success_condition: 'device.audio.driver_status == "updated" && audio.output == true',
    difficulty_tier: 1,
  },
  {
    id: 'tech-6',
    title: 'Resolution Fix',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Output Devices/VDU (change resolution)',
      concept: 'Display Resolution',
    },
    client: {
      name: 'Aunty Sheryl',
      role: 'Receptionist',
      mood: 'Angry',
      dialogue_start: 'Everything big-big on the screen and I can’t see my work properly!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 9,
      network_status: 'Connected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Display Settings.',
      'Locate Screen Resolution.',
      'Change from 800x600 to 1920x1080.',
      'Confirm changes.',
    ],
    success_condition: 'display.resolution == "1920x1080"',
    difficulty_tier: 1,
  },
  {
    id: 'tech-7',
    title: 'Bloatware Purge',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Application Software (uninstall bloatware)',
      concept: 'Uninstall Programs',
    },
    client: {
      name: 'Mr. Kareem',
      role: 'Small Business Owner',
      mood: 'Chill',
      dialogue_start: 'This Toolbar_Helper_Pro thing keep popping up. Remove it please.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 15,
      network_status: 'Connected',
      file_system: ['C:/Program Files/Toolbar_Helper_Pro/app.exe'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Control Panel or Apps & Features.',
      'Find Toolbar_Helper_Pro.',
      'Uninstall it.',
      'Confirm it is removed from the program list.',
    ],
    success_condition: 'app.installed("Toolbar_Helper_Pro") == false',
    difficulty_tier: 1,
  },
  {
    id: 'tech-8',
    title: 'System Specs',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Hardware Specifications (RAM, CPU speed)',
      concept: 'System Information',
    },
    client: {
      name: 'Jayden',
      role: 'Gamer',
      mood: 'Confused',
      dialogue_start: 'Can I run this game? I only know it say 8GB RAM required.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 13,
      network_status: 'Connected',
      file_system: ['C:/Games/SpecSheet.txt'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open System Information.',
      'Find installed RAM and CPU speed.',
      'Compare with the game requirements shown in the prompt.',
      'Give the client a pass/fail answer.',
    ],
    success_condition: 'specs.checked == true',
    difficulty_tier: 1,
  },
  {
    id: 'tech-9',
    title: 'Power Saver',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Device Management (Power & Sleep settings)',
      concept: 'Power Management',
    },
    client: {
      name: 'Nia',
      role: 'Student',
      mood: 'Chill',
      dialogue_start: 'Battery does drop fast. Set it to save power when I studying please.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 8,
      network_status: 'Connected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Power & Sleep settings.',
      'Set Screen to turn off after 2 minutes on battery.',
      'Save the settings.',
    ],
    success_condition: 'power.screen_off_minutes_on_battery == 2',
    difficulty_tier: 1,
  },
  {
    id: 'tech-10',
    title: 'The First Backup',
    rank: 1,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Secondary Storage (copy files to external drive)',
      concept: 'Backup / External Drive',
    },
    client: {
      name: 'Coach Lennox',
      role: 'Sports Coach',
      mood: 'Panic',
      dialogue_start: 'If this laptop mash up I losing all my team files. Put it on the external drive nah.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'home_helper',
    },
    initial_state: {
      cpu_load: 11,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Documents/Team/roster.docx', 'E:/'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open File Explorer.',
      'Select the critical documents folder/files.',
      'Drag them to External Drive (E:).',
      'Confirm files exist on E:.',
    ],
    success_condition: 'drive.E.contains("roster.docx") == true',
    difficulty_tier: 1,
  },

  {
    id: 'tech-11',
    title: 'Printer Jam',
    rank: 2,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Output Devices/Printers (clear spooler queue)',
      concept: 'Print Spooler',
    },
    client: {
      name: 'Ms. Indra',
      role: 'Secretary',
      mood: 'Angry',
      dialogue_start: 'Printer queue jam up! Is the same document printing 20 times!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 20,
      network_status: 'Connected',
      file_system: ['C:/System/Spool/printjob_001.spl', 'C:/System/Spool/printjob_002.spl'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Printers & Scanners.',
      'Open the printer queue.',
      'Cancel all pending print jobs.',
      'Confirm queue is empty.',
    ],
    success_condition: 'printer.queue.count == 0',
    difficulty_tier: 2,
  },
  {
    id: 'tech-12',
    title: 'The Sticky Key',
    rank: 2,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Input Devices (configure Filter Keys)',
      concept: 'Accessibility / Filter Keys',
    },
    client: {
      name: 'Uncle T',
      role: 'Mechanic',
      mood: 'Confused',
      dialogue_start: 'One key keep repeating like it have a mind of its own.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Accessibility settings.',
      'Navigate to Keyboard options.',
      'Enable Filter Keys (or adjust repeat delay).',
      'Confirm typing no longer repeats unexpectedly.',
    ],
    success_condition: 'keyboard.filter_keys.enabled == true',
    difficulty_tier: 2,
  },
  {
    id: 'tech-13',
    title: 'Antivirus Scan',
    rank: 2,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Virus Protection (scan and quarantine threats)',
      concept: 'Deep Scan / Quarantine',
    },
    client: {
      name: 'Rohan',
      role: 'Student',
      mood: 'Panic',
      dialogue_start: 'I click a weird link… now the laptop acting shady. Run a deep scan please!',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 35,
      network_status: 'Connected',
      file_system: ['C:/Downloads/sus_file.exe'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Defend (antivirus).',
      'Start a Deep Scan.',
      'Wait for scan results.',
      'Quarantine detected threats.',
      'Confirm threat list is cleared or quarantined.',
    ],
    success_condition: 'defend.threats.active == 0 && defend.threats.quarantined >= 1',
    difficulty_tier: 2,
  },
  {
    id: 'tech-14',
    title: 'Disk Partition',
    rank: 2,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Storage (partition concepts)',
      concept: 'Partitions / Volumes',
    },
    client: {
      name: 'Mr. Dale',
      role: 'Shop Manager',
      mood: 'Chill',
      dialogue_start: 'Make a D: drive for my business files so it separate from the system.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Connected',
      file_system: ['Disk0: 120GB (C: only)'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Disk Management.',
      'Shrink the C: volume to free space.',
      'Create a new simple volume from unallocated space.',
      'Assign drive letter D:.',
      'Format as NTFS (or default).',
    ],
    success_condition: 'disk.volumes.contains("D:") == true',
    difficulty_tier: 2,
  },
  {
    id: 'tech-15',
    title: 'Password Reset',
    rank: 2,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Passwords/Access Restrictions (reset user password)',
      concept: 'Account Management',
    },
    client: {
      name: 'Ms. Patrice',
      role: 'HR Clerk',
      mood: 'Panic',
      dialogue_start: 'User forget the login and payroll due today! Reset it quick nah.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: ['C:/System/Accounts/users.json'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Admin Tools / User Accounts.',
      'Select the affected user account.',
      'Choose Reset Password.',
      'Set a temporary password.',
      'Confirm user can login with the temporary password.',
    ],
    success_condition: 'account.user.password_reset == true',
    difficulty_tier: 2,
  },
  {
    id: 'tech-16',
    title: 'Extension Nightmare',
    rank: 2,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Internet Concepts (malicious extension removal)',
      concept: 'Browser Extensions / Redirects',
    },
    client: {
      name: 'Omar',
      role: 'Clerk',
      mood: 'Angry',
      dialogue_start: 'Every time I open the browser it carry me to some weird site. Fix it now.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 16,
      network_status: 'Connected',
      file_system: ['Browser/Extensions/quick_search_plus'],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open Browser settings.',
      'Navigate to Extensions/Add-ons.',
      'Identify the suspicious extension causing redirects.',
      'Remove/disable the extension.',
      'Confirm homepage/search no longer redirects.',
    ],
    success_condition: 'browser.redirects == false && browser.extensions.malicious == 0',
    difficulty_tier: 2,
  },
  {
    id: 'tech-17',
    title: 'Zip & Send',
    rank: 2,
    csec_alignment: {
      section: 'Section 5',
      objective: 'File Organization (compress to zip)',
      concept: 'Compression / ZIP',
    },
    client: {
      name: 'Kayla',
      role: 'Photographer',
      mood: 'Chill',
      dialogue_start: 'I need to email the photos but it too heavy. Zip it up for me.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 14,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Pictures/EventShoot/'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Locate the photos folder.',
      'Right-click the folder.',
      'Choose Compress / Send to ZIP.',
      'Confirm a .zip file is created.',
    ],
    success_condition: 'file.exists("EventShoot.zip") == true',
    difficulty_tier: 2,
  },
  {
    id: 'tech-18',
    title: 'Command Line Intro',
    rank: 2,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Command Driven Interface (dir/ls)',
      concept: 'Terminal Basics',
    },
    client: {
      name: 'Mr. Noel',
      role: 'IT Assistant',
      mood: 'Chill',
      dialogue_start: 'Boss say I must learn terminal basics. Show me how to list files quick.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 9,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Documents/tutorial.txt'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      "Type: dir",
      'Press Enter to list files.',
      'Confirm files display in terminal output.',
    ],
    success_condition: 'terminal.last_command == "dir" && terminal.last_output.contains("tutorial.txt") == true',
    difficulty_tier: 2,
  },
  {
    id: 'tech-19',
    title: 'System Restore',
    rank: 2,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Recovery Procedures (system restore)',
      concept: 'Rollback / Restore Point',
    },
    client: {
      name: 'Mummy Cheryl',
      role: 'Office Worker',
      mood: 'Panic',
      dialogue_start: 'After the update the PC keep crashing. Can we roll it back to how it was?',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 25,
      network_status: 'Connected',
      file_system: ['C:/System/RestorePoints/2026-01-23'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Recovery settings.',
      'Choose System Restore.',
      'Select the restore point from 2 days ago.',
      'Confirm restore and restart (simulated).',
    ],
    success_condition: 'system.restore.completed == true && system.crash_rate == 0',
    difficulty_tier: 2,
  },
  {
    id: 'tech-20',
    title: 'Hardware Upgrade (Sim)',
    rank: 2,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Primary Storage (RAM upgrade)',
      concept: 'RAM Modules',
    },
    client: {
      name: 'Dario',
      role: 'Repair Tech',
      mood: 'Chill',
      dialogue_start: 'Customer want more RAM. In the sim, swap 4GB for 8GB and boot it back up.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'techfix_shop',
    },
    initial_state: {
      cpu_load: 8,
      network_status: 'Disconnected',
      file_system: ['VirtualCase/ram_slot_1=4GB', 'VirtualCase/ram_slot_2=empty'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open the virtual case.',
      'Remove the 4GB RAM stick from slot 1.',
      'Insert an 8GB RAM stick into slot 1.',
      'Boot the system and confirm RAM shows as 8GB.',
    ],
    success_condition: 'hardware.ram_gb == 8',
    difficulty_tier: 2,
  },

  {
    id: 'tech-21',
    title: 'Is the Internet Down?',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Data Communication (ping / connectivity test)',
      concept: 'Ping / Packet Loss',
    },
    client: {
      name: 'Ms. Alana',
      role: 'Rum Shop Cashier',
      mood: 'Panic',
      dialogue_start: 'POS not loading! Check if the internet dead please!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 22,
      network_status: 'Disconnected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Run a ping test to a public host.',
      "Type: ping google.com",
      'Observe request timed out.',
      'Report: no external connectivity.',
    ],
    success_condition: 'terminal.last_command == "ping google.com" && ping.packet_loss_percent == 100',
    difficulty_tier: 3,
  },
  {
    id: 'tech-22',
    title: 'IP Config',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Network Technology (APIPA 169.254, renew IP)',
      concept: 'DHCP / IP Renew',
    },
    client: {
      name: 'Mr. Joel',
      role: 'Office Manager',
      mood: 'Angry',
      dialogue_start: 'Computer can’t connect to the network and it showing some strange 169 address.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Disconnected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Check IP configuration.',
      'Confirm the IP is 169.254.x.x (APIPA).',
      'Force renew the IP lease.',
      "Run: ipconfig /renew (or the BrightOS equivalent)",
    ],
    success_condition: 'network.ip.startsWith("192.168.") == true && network_status == "Connected"',
    difficulty_tier: 3,
  },
  {
    id: 'tech-23',
    title: 'Static IP',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Intranet/LAN (configure static IPv4)',
      concept: 'Static Addressing',
    },
    client: {
      name: 'Ms. Sade',
      role: 'School Admin',
      mood: 'Confused',
      dialogue_start: 'Printer keeps changing address. Set a static IP so lab can always print.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 14,
      network_status: 'Connected',
      file_system: ['Printer: HP-LAB-01'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Network settings.',
      'Select the printer network configuration.',
      'Set IPv4 to static.',
      'Enter a static IP (example: 192.168.0.50), subnet mask, gateway.',
      'Save and confirm printer reachable.',
    ],
    success_condition: 'printer.ip == "192.168.0.50" && printer.reachable == true',
    difficulty_tier: 3,
  },
  {
    id: 'tech-24',
    title: 'DNS Switch',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Internet Concepts (DNS change)',
      concept: 'DNS Resolver',
    },
    client: {
      name: 'Andre',
      role: 'Barbershop Owner',
      mood: 'Panic',
      dialogue_start: 'WhatsApp Web not loading on the shop PC. Somebody say change DNS. Do it for me.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 13,
      network_status: 'Slow',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Network adapter settings.',
      'Edit IPv4 DNS settings.',
      'Switch DNS from Automatic to Manual.',
      'Set DNS to 8.8.8.8.',
      'Save and confirm website loads.',
    ],
    success_condition: 'network.dns.primary == "8.8.8.8" && network_status == "Connected"',
    difficulty_tier: 3,
  },
  {
    id: 'tech-25',
    title: 'Router Setup',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Physical Access Restrictions (change default router password)',
      concept: 'Router Admin Credentials',
    },
    client: {
      name: 'Mr. Singh',
      role: 'Mini-Mart Owner',
      mood: 'Angry',
      dialogue_start: 'Somebody tell me router still using default password. That risky. Fix it now.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open Browser.',
      'Navigate to 192.168.0.1.',
      'Login with current admin credentials (simulated).',
      'Change the default admin password to a strong password.',
      'Save and confirm logout/login works.',
    ],
    success_condition: 'router.admin_password_changed == true',
    difficulty_tier: 3,
  },
  {
    id: 'tech-26',
    title: 'Wi‑Fi Security',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Wireless Network Tech (WEP to WPA2)',
      concept: 'Encryption Mode',
    },
    client: {
      name: 'Janelle',
      role: 'Community Center Staff',
      mood: 'Panic',
      dialogue_start: 'Wi‑Fi getting hacked easy. It set to WEP. Change it to WPA2 please!',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open router admin page.',
      'Locate Wireless Security settings.',
      'Change security mode from WEP to WPA2.',
      'Set a strong Wi‑Fi password.',
      'Save and confirm devices reconnect.',
    ],
    success_condition: 'router.wifi.security == "WPA2"',
    difficulty_tier: 3,
  },
  {
    id: 'tech-27',
    title: 'Trace the Drop',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Transmission Media (tracert to find packet loss point)',
      concept: 'Traceroute',
    },
    client: {
      name: 'Dion',
      role: 'Call Center Agent',
      mood: 'Angry',
      dialogue_start: 'Connection dropping mid-call. Use tracert and see where it failing!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 20,
      network_status: 'Slow',
      file_system: [],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Run traceroute to a website.',
      "Type: tracert google.com",
      'Identify the hop where timeouts start.',
      'Report likely packet loss point.',
    ],
    success_condition: 'terminal.last_command == "tracert google.com" && trace.loss_hop_index >= 1',
    difficulty_tier: 3,
  },
  {
    id: 'tech-28',
    title: 'Port Forwarding',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Web Server/HTTP (open port 80)',
      concept: 'Port Forwarding',
    },
    client: {
      name: 'Kurt',
      role: 'Web Developer',
      mood: 'Confused',
      dialogue_start: 'My local web server not reachable outside. Open port 80 on the router.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Connected',
      file_system: ['Server: local_http (port 80)'],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open router admin page.',
      'Go to Port Forwarding.',
      'Create rule: external port 80 -> internal IP (server) port 80.',
      'Save changes.',
      'Confirm outside request can reach server (simulated).',
    ],
    success_condition: 'router.port_forwarding.contains("80") == true',
    difficulty_tier: 3,
  },
  {
    id: 'tech-29',
    title: 'MAC Filtering',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Security Measures (block device MAC)',
      concept: 'MAC Filtering',
    },
    client: {
      name: 'Asha',
      role: 'Cafe Owner',
      mood: 'Angry',
      dialogue_start: 'Neighbour keep stealing Wi‑Fi. Block their MAC address, please.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: ['Router/Clients: 3 (one unknown)'],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open router admin page.',
      'View connected devices list.',
      'Identify the unknown MAC address (provided in the mission UI).',
      'Add it to the blocked list (MAC filtering).',
      'Confirm device is disconnected.',
    ],
    success_condition: 'router.blocked_macs.contains(unknown_device.mac) == true',
    difficulty_tier: 3,
  },
  {
    id: 'tech-30',
    title: 'FTP Transfer',
    rank: 3,
    csec_alignment: {
      section: 'Section 4',
      objective: 'File Transfer Protocol (upload file)',
      concept: 'FTP Client',
    },
    client: {
      name: 'Nico',
      role: 'Freelancer',
      mood: 'Chill',
      dialogue_start: 'I need to upload the website file via FTP. Walk me through it.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'smallbiz_admin',
    },
    initial_state: {
      cpu_load: 15,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Desktop/index.html'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal or FTP client (simulated via Terminal).',
      'Connect to FTP server with host/user/pass (provided by mission).',
      'Upload index.html to /public_html.',
      'Confirm upload success message.',
    ],
    success_condition: 'ftp.uploaded.contains("index.html") == true',
    difficulty_tier: 3,
  },

  {
    id: 'tech-31',
    title: 'Mechanic (Automation App)',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Problem-Solving & Program Design (drag-and-drop logic)',
      concept: 'Automation Blocks',
    },
    client: {
      name: 'Shawn',
      role: 'Junior Dev',
      mood: 'Confused',
      dialogue_start: 'Boss give me the Automation App. I not sure how to build a simple rule chain.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: ['AutomationApp/projects/blank.flow'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open Automation App.',
      'Create a new flow.',
      'Add an input block and an output block.',
      'Connect blocks and run test.',
    ],
    success_condition: 'automation.flow.valid == true',
    difficulty_tier: 4,
  },
  {
    id: 'tech-32',
    title: 'Auto‑Shutdown',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'If-Then Logic (time-based rule)',
      concept: 'Conditional Rules',
    },
    client: {
      name: 'Ms. Ria',
      role: 'Office Supervisor',
      mood: 'Chill',
      dialogue_start: 'After 10pm the lab should shutdown automatically. Build the rule.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: ['AutomationApp/projects/auto_shutdown.flow'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open Automation App and load auto_shutdown.flow.',
      'Create condition: IF time > 22:00.',
      'Set action: THEN Shutdown.',
      'Run simulation test with time=22:01.',
    ],
    success_condition: 'automation.outputs.shutdown_triggered == true',
    difficulty_tier: 4,
  },
  {
    id: 'tech-33',
    title: 'Spam Filter',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Problem Solving (keyword detection rule)',
      concept: 'String Contains',
    },
    client: {
      name: 'Mr. Clive',
      role: 'Office IT',
      mood: 'Angry',
      dialogue_start: 'Spam does flood the inbox. Build a rule: if subject have “Winner” move it to Spam.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: ['AutomationApp/projects/spam_filter.flow'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open Automation App.',
      'Add condition: IF subject CONTAINS "Winner".',
      'Add action: THEN move to Spam folder.',
      'Test with sample email subject “Winner! Claim now”.',
    ],
    success_condition: 'automation.outputs.moved_to_spam == true',
    difficulty_tier: 4,
  },
  {
    id: 'tech-34',
    title: 'Temp Control',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Input/Process/Output (sensor rule)',
      concept: 'Threshold / Fan Control',
    },
    client: {
      name: 'Kay',
      role: 'Support Engineer',
      mood: 'Panic',
      dialogue_start: 'CPU temperature high. Build the rule: if temp > 80 then fan speed 100.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 55,
      network_status: 'Connected',
      file_system: ['AutomationApp/projects/temp_control.flow'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open Automation App.',
      'Create IF condition: CPU_Temp > 80.',
      'Set THEN action: Fan_Speed = 100.',
      'Test with CPU_Temp = 85.',
    ],
    success_condition: 'automation.outputs.fan_speed == 100',
    difficulty_tier: 4,
  },
  {
    id: 'tech-35',
    title: 'Login Script',
    rank: 4,
    csec_alignment: {
      section: 'Section 5',
      objective: 'Validation Checks (fix password validation)',
      concept: 'Input Validation',
    },
    client: {
      name: 'Mika',
      role: 'Intern',
      mood: 'Confused',
      dialogue_start: 'The script accepting the word “Password” as a password… that can’t be right.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 20,
      network_status: 'Connected',
      file_system: ['C:/Projects/login_script.psc'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open the script in the Automation App editor.',
      'Add validation: reject password if it equals "Password" (case-insensitive).',
      'Add minimum length validation (e.g., 8 chars).',
      'Run test cases and confirm invalid passwords are rejected.',
    ],
    success_condition: 'validation.rejects_common_password == true && validation.min_length >= 8',
    difficulty_tier: 4,
  },
  {
    id: 'tech-36',
    title: 'Batch Rename',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Looping Constructs (for loop rename)',
      concept: 'FOR Loop',
    },
    client: {
      name: 'Trina',
      role: 'Content Creator',
      mood: 'Chill',
      dialogue_start: 'Rename all photos in the folder to img_1, img_2… using a loop.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 14,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Pictures/Batch/001.jpg', 'C:/Users/Student/Pictures/Batch/002.jpg'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open Automation App.',
      'Create loop: FOR each file in folder.',
      'Rename(file, "img_" + count).',
      'Run and confirm files renamed sequentially.',
    ],
    success_condition: 'files.renamed_prefix == "img_" && files.renamed_count == files.total',
    difficulty_tier: 4,
  },
  {
    id: 'tech-37',
    title: 'Data Type Fix',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Data Types (text vs integer)',
      concept: 'Type Conversion',
    },
    client: {
      name: 'Imran',
      role: 'Junior Analyst',
      mood: 'Confused',
      dialogue_start: 'Script failing because it adds “5” (text) to 10 (integer). Fix it.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Connected',
      file_system: ['C:/Projects/type_bug.psc'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open the script.',
      'Identify the variables with mismatched types.',
      'Convert "5" to integer before adding.',
      'Run test and confirm result is 15.',
    ],
    success_condition: 'script.output == 15',
    difficulty_tier: 4,
  },
  {
    id: 'tech-38',
    title: 'The Infinite Loop',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Characteristics of Algorithms (avoid infinite loop)',
      concept: 'While Loop / Break',
    },
    client: {
      name: 'Kiesha',
      role: 'QA Tester',
      mood: 'Panic',
      dialogue_start: 'Automation process crashing CPU. It look like while(true). Add a break!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 95,
      network_status: 'Connected',
      file_system: ['C:/Projects/infinite_loop.psc'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open the script.',
      'Locate the while(true) loop.',
      'Add a break condition based on a counter or completion flag.',
      'Run and confirm CPU usage stabilizes.',
    ],
    success_condition: 'script.terminates == true && cpu_load < 40',
    difficulty_tier: 4,
  },
  {
    id: 'tech-39',
    title: 'Variable Swap',
    rank: 4,
    csec_alignment: {
      section: 'Section 2',
      objective: 'Variables (swap values)',
      concept: 'Temporary Variable',
    },
    client: {
      name: 'Mr. Lyle',
      role: 'Tutor',
      mood: 'Chill',
      dialogue_start: 'Show the student how to swap A=5 and B=10 so A=10 and B=5.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 10,
      network_status: 'Connected',
      file_system: ['AutomationApp/projects/variable_swap.flow'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Set A = 5 and B = 10.',
      'Use a temporary variable T = A.',
      'Set A = B.',
      'Set B = T.',
      'Run and confirm A=10, B=5.',
    ],
    success_condition: 'vars.A == 10 && vars.B == 5',
    difficulty_tier: 4,
  },
  {
    id: 'tech-40',
    title: 'Sorting Algo',
    rank: 4,
    csec_alignment: {
      section: 'Section 3',
      objective: 'Manipulate Lists/Arrays (bubble sort)',
      concept: 'Bubble Sort',
    },
    client: {
      name: 'Sasha',
      role: 'Student',
      mood: 'Confused',
      dialogue_start: 'Teacher say bubble sort the files by size. I need a visual way to do it.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'automation_lab',
    },
    initial_state: {
      cpu_load: 15,
      network_status: 'Connected',
      file_system: ['List: [120KB, 40KB, 220KB, 10KB]'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open the bubble sort blocks.',
      'Compare adjacent elements and swap if out of order.',
      'Repeat passes until no swaps occur.',
      'Confirm list is sorted ascending.',
    ],
    success_condition: 'list.sorted == true',
    difficulty_tier: 4,
  },

  {
    id: 'tech-41',
    title: 'The Phantom Connection',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Electronic Eavesdropping (netstat, kill PID)',
      concept: 'Netstat / Suspicious Connections',
    },
    client: {
      name: 'Mrs. Baptiste',
      role: 'Finance Officer',
      mood: 'Panic',
      dialogue_start: 'Something connecting out to a foreign IP. Use netstat and shut it down now!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 45,
      network_status: 'Connected',
      file_system: ['C:/Logs/net_connections.log'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal', 'Task Manager'],
    steps_to_solve: [
      'Open Terminal.',
      'Run netstat to list active connections with PIDs.',
      'Identify the connection to the foreign IP (flagged in output).',
      'Note the PID.',
      'End the process by PID using Task Manager (simulated).',
    ],
    success_condition: 'network.suspicious_connection.active == false',
    difficulty_tier: 5,
  },
  {
    id: 'tech-42',
    title: 'Firewall Rules',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Software Restrictions (block inbound port)',
      concept: 'Firewall / Port Blocking',
    },
    client: {
      name: 'Mr. Hinds',
      role: 'Network Officer',
      mood: 'Angry',
      dialogue_start: 'Block all incoming traffic on port 23. Telnet is too risky.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 20,
      network_status: 'Connected',
      file_system: ['Firewall: enabled'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Firewall settings.',
      'Create a new inbound rule.',
      'Select Port rule and set port 23.',
      'Set action to Block.',
      'Confirm rule is enabled.',
    ],
    success_condition: 'firewall.inbound.blocked_ports.contains(23) == true',
    difficulty_tier: 5,
  },
  {
    id: 'tech-43',
    title: 'Phishing Investigator',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Identity Theft (recognize phishing)',
      concept: 'Email Header / Spoofing',
    },
    client: {
      name: 'Tariq',
      role: 'Helpdesk',
      mood: 'Confused',
      dialogue_start: 'We get an email from admin@g00gle.com asking for passwords. Is it legit?',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 12,
      network_status: 'Connected',
      file_system: ['C:/Mail/inbox.eml'],
      terminal_history: [],
    },
    tools_allowed: ['Browser'],
    steps_to_solve: [
      'Open the email details/header view.',
      'Identify suspicious sender domain: admin@g00gle.com.',
      'Flag the email as Phishing.',
      'Report the indicator of compromise (spoofed domain).',
    ],
    success_condition: 'mail.flagged_phishing == true',
    difficulty_tier: 5,
  },
  {
    id: 'tech-44',
    title: 'Hidden Process',
    rank: 5,
    csec_alignment: {
      section: 'Section 1',
      objective: 'Systems Software (hidden processes)',
      concept: 'Terminal Process List',
    },
    client: {
      name: 'Ms. Nala',
      role: 'IT Security',
      mood: 'Panic',
      dialogue_start: 'Malware hiding from the GUI. Use terminal to find it and confirm what running.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 70,
      network_status: 'Connected',
      file_system: ['C:/System/cache/hidden_proc.bin'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Run the process list command (simulated top/tasklist).',
      'Identify abnormal process name (flagged).',
      'Capture PID for incident report.',
    ],
    success_condition: 'incident.pid_identified == true',
    difficulty_tier: 5,
  },
  {
    id: 'tech-45',
    title: 'Force Delete',
    rank: 5,
    csec_alignment: {
      section: 'Section 1',
      objective: 'File Management (locked file removal - simulated)',
      concept: 'Force Delete (Simulated)',
    },
    client: {
      name: 'Mr. Denzel',
      role: 'SysAdmin',
      mood: 'Angry',
      dialogue_start: 'File locked and can’t delete from GUI. Use terminal force-delete it (sim only).',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 40,
      network_status: 'Connected',
      file_system: ['C:/Quarantine/malware.exe (locked)'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Attempt delete of the file.',
      'Use the simulator’s safe force-delete command to remove it.',
      'Confirm the file no longer exists.',
    ],
    success_condition: 'file.exists("C:/Quarantine/malware.exe") == false',
    difficulty_tier: 5,
  },
  {
    id: 'tech-46',
    title: 'Encryption',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Encryption (protect sensitive folder)',
      concept: 'Folder Encryption',
    },
    client: {
      name: 'Dr. Mendez',
      role: 'Clinic Admin',
      mood: 'Panic',
      dialogue_start: 'We sending patient data. Encrypt the folder before it go anywhere.',
    },
    brightos_desktop: {
      device: 'Laptop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 14,
      network_status: 'Connected',
      file_system: ['C:/Users/Student/Documents/Clinic/Records/'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Locate the sensitive folder.',
      'Open folder properties.',
      'Enable encryption (simulated toggle).',
      'Confirm folder shows encrypted status.',
    ],
    success_condition: 'folder.encrypted("C:/Users/Student/Documents/Clinic/Records/") == true',
    difficulty_tier: 5,
  },
  {
    id: 'tech-47',
    title: 'Log Forensics',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Computer Fraud (analyze access logs)',
      concept: 'Log Review / Brute Force Timestamp',
    },
    client: {
      name: 'Ms. Priya',
      role: 'Security Analyst',
      mood: 'Chill',
      dialogue_start: 'Read access.log and find the timestamp of the brute force attack.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 22,
      network_status: 'Connected',
      file_system: ['C:/Logs/access.log'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal'],
    steps_to_solve: [
      'Open Terminal.',
      'Open or search access.log.',
      'Identify repeated failed login attempts.',
      'Extract the first timestamp where the brute force begins.',
    ],
    success_condition: 'forensics.bruteforce_timestamp != ""',
    difficulty_tier: 5,
  },
  {
    id: 'tech-48',
    title: 'SQL Injection (Sim)',
    rank: 5,
    csec_alignment: {
      section: 'Section 5',
      objective: 'Validation (prevent injection)',
      concept: 'SQL Injection / Input Sanitization',
    },
    client: {
      name: 'Aron',
      role: 'Web Admin',
      mood: 'Angry',
      dialogue_start: 'Form accepts \' OR 1=1. Patch the input validation in the sim.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 18,
      network_status: 'Connected',
      file_system: ['C:/WebApp/login_form.js'],
      terminal_history: [],
    },
    tools_allowed: ['Automation App'],
    steps_to_solve: [
      'Open the validation rules for the login form.',
      'Detect and reject inputs containing SQL meta characters/patterns.',
      'Use parameterized queries (simulated toggle).',
      'Test with input: \' OR 1=1 and confirm rejection.',
    ],
    success_condition: 'web.validation.blocks_sql_injection == true',
    difficulty_tier: 5,
  },
  {
    id: 'tech-49',
    title: 'Ransomware Recovery',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Recovery Procedures (restore from backup)',
      concept: 'Backup Restore',
    },
    client: {
      name: 'Mr. Watson',
      role: 'School Principal',
      mood: 'Panic',
      dialogue_start: 'Screen red and files locked! Restore from the backup you made earlier!',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 60,
      network_status: 'Disconnected',
      file_system: ['C:/Users/Student/Documents/ (encrypted)', 'E:/Backup/'],
      terminal_history: [],
    },
    tools_allowed: ['Settings'],
    steps_to_solve: [
      'Open Backup/Restore tool.',
      'Select external backup drive (E:).',
      'Choose latest backup set.',
      'Restore documents to original location (simulated).',
      'Confirm files are readable again.',
    ],
    success_condition: 'files.restored == true && ransomware.lock_screen == false',
    difficulty_tier: 5,
  },
  {
    id: 'tech-50',
    title: 'The Exam',
    rank: 5,
    csec_alignment: {
      section: 'Section 4',
      objective: 'Integrated Security Scenario (identify entry, kill process, restore, patch firewall)',
      concept: 'Incident Response',
    },
    client: {
      name: 'CSEC Proctor',
      role: 'Examiner',
      mood: 'Chill',
      dialogue_start: 'Simulated company hack. Identify entry point, kill process, restore data, patch firewall.',
    },
    brightos_desktop: {
      device: 'Desktop',
      wallpaper_pool: WALLPAPERS,
      logo: { src: '/BrightEdLogo.png', placement: 'top-left' },
      ui_preset: 'csec_soc',
    },
    initial_state: {
      cpu_load: 85,
      network_status: 'Slow',
      file_system: ['C:/Logs/access.log', 'C:/Quarantine/', 'E:/Backup/'],
      terminal_history: [],
    },
    tools_allowed: ['Terminal', 'Task Manager', 'Settings'],
    steps_to_solve: [
      'Use logs to identify the likely entry point (phishing or exposed port shown in hints).',
      'Use netstat/task list to identify the malicious process PID.',
      'End the malicious process.',
      'Restore encrypted or deleted files from backup.',
      'Add firewall rule to block the exploited port.',
      'Confirm system returns to stable state.',
    ],
    success_condition: 'incident.resolved == true',
    difficulty_tier: 5,
  },
];

export function getMissionById(id: string) {
  return CSEC_ROADMAP_MISSIONS.find((m) => m.id === id) || null;
}
